### ISSUE TITLE
Add support for discriminated unions/sum types

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#539] opened 2023-01-19 07:59 UTC
We have been envisioning redesign of discriminated unions, which we have not really implemented yet.

Related issues: #233, #244, #440

In all of our discussions, we seem to have converged on the idea of having (non-inductive, non-recursive) ADTs instead of discriminated unions. We have to think about the syntax, but following other languages, it should look similar to the ones below, modulo renaming of tokens:

```
// similar to Result in Rust
type Result[T, E] = Ok(T) | Err(E)
// similar to Either in Scala
type Either[L, R] = Left(L) | Right(R)
```

What we have learned from Apalache is that discriminated unions almost immediately require constructors for the options such as `Ok` and `Err` in the above code, see [an example]( https://github.com/informalsystems/apalache/blob/8baab28cf4d46b02a9d2f5b8ebceebfa2b972884/src/tla/Option.tla#L13-L32). Otherwise, they stay open and are not very useful. The good thing about the ADT syntax is that it also introduces constructors for the options.

As a first step, we would definitely avoid recursive ADTs. It requires a kind of reasoning that is different from what is normally done in TLA+. Moreover, there is no practical need for recursive ADTs yet. We may revisit this decision in the future.

**Comment by shonfeder** [comment] 2023-01-19 13:15
Afaiu, the record-based discriminated unions are a totally workable basis for a sum type that can be with use with other ADTs (i.e. product types), but I agree that the tagged constructor/deconstruct notation is nicer than having to go through records with a special field :)

**Comment by shonfeder** [comment] 2023-07-10 22:52
Seems to be a duplicate of #244

**Closed by shonfeder** 2023-07-10 22:52 UTC
Labels: Flanguage, product-priority-general
