### ISSUE TITLE
Introduce a surface syntax for record updates

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#876] opened 2023-05-09 07:29 UTC
As everybody noticed, the current syntax for record updates is cumbersome. Here is an example:

https://github.com/informalsystems/quint/blob/4ac41a437fb800133089398773b301818d1175ca/examples/cosmos/ics20/ics20.qnt#L80-L82

The truth is that there is no syntax for record updates. This is simply an operator in the standard form.

As already discussed in #570, it would be great to have a more intuitive syntax for record updates, especially, for updating multiple fields. However, we do not want to introduce a more complex operator for record updates. This calls for a surface syntax. In the spirit of the syntax proposed by @shonfeder in #570, I am proposing a special syntax form in the grammar. The [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) looks like a natural candidate:

```
{
  ...chainState,
  bank: bankResult.accounts,
  outPackets: chainState.outPackets.union(Set(packet))
}
```

Note that this will be only a surface syntax, which will be immediately replaced with the `with` operator by the parser. By doing so, we will keep the IR simple, and the users happier.

An alternative is the [rust syntax](https://doc.rust-lang.org/book/ch05-01-defining-structs.html#creating-instances-from-other-instances-with-struct-update-syntax) for struct updates. However, the rust syntax requires a struct type, which we would like to avoid.

**Comment by shonfeder** [comment] 2023-05-09 12:01
There is also the ocaml syntax, which is very clear imo:

```
{ oldRec with new1 = 2, new2 = 3  }
```

**Comment by shonfeder** [comment] 2023-05-09 12:55
This is a duplicate of https://github.com/informalsystems/quint/issues/816

**Closed by shonfeder** 2023-05-09 12:55 UTC
Labels: usability, Flanguage, feedback

**Comment by konnov** [comment] 2023-05-09 15:34
>> There is also the ocaml syntax, which is very clear imo:
>
> `{ oldRec with new1 = 2, new2 = 3  }`

While I share the sentiment of OCaml syntax over JS syntax, I believe we would get more delight points from using the more familiar JS/Rust syntax.

**Comment by shonfeder** [comment] 2023-05-09 15:45
I guess it's just a question of `...` vs. `with`, so the stakes are pretty low. I think it goes against our design principles to pick a more cryptic operator, but maybe we'll find the splat syntax can be used for collections as well.
