### ISSUE TITLE
Implement a command similar to `who` in REPL

### ISSUE THREAD

**Issue by konnov** [informalsystems/quint#795] opened 2023-04-11 16:44 UTC
As mentioned by @lasarojc, it would be great to have a command that behaves similar to [who](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-whos) of IPython.

**Comment by lasarojc** [comment] 2023-04-13 16:08
On a test failure, the command could be automatically executed to show the state in which the failure happened. Delight points if the output is in the form of a state transaction that can be easily copied and pasted into the REPL :)

**Comment by shonfeder** [comment] 2024-01-09 19:58
This is a duplicate of #446

**Closed by shonfeder** 2024-01-09 19:58 UTC
Labels: feedback, repl
